# ROS bag Topics
ros_parameters:
  ## Sensors
  # lidar_topic: '/rslidar_points'
  # camera_topic: '/camera/camera/color/image_raw'
  # caminfo_topic: '/camera/camera/color/camera_info'
  lidar_topic: '/wamv/sensors/lidars/lidar_sensor/points'
  camera_topic: '/wamv/sensors/cameras/camera_sensor/optical/image_raw'
  caminfo_topic: '/wamv/sensors/cameras/camera_sensor/optical/camera_info'

  ## DRIFT
  pose_topic: '/drift/pose'

  ## Sensor Fronend Processing
  det_mask_topic: '/cam_det/segmentation_mask'
  annot_topic: '/cam_det/annotated_image'
  filt_pcd_topic: '/lidars/filtered_pcd'      # Filtered LiDAR pcd
  lm_det_topic: '/cam_lidar/detection/landmarks'

  ## Semantic Mapping
  overlay_topic: '/convBKI/debug/lidar_camera_overlay'
  semantic_pcd_topic: '/convBKI/semantic_pcd'
  global_pcd_topic: '/convBKI/global_semantic_pcd'
  ogm_topic: '/convBKI/OGM_global'
  map_topic: '/convBKI/SemMap_global'                 # not using rn
  var_topic: '/convBKI/VarMap_global'
  # global_map_topic: '/global_semantic_map'
  # global_var_topic: '/global_variance_map'

  ## Object SLAM
  anchor_topic: '/obj_slam/gtsam/pose_anchor'
  keyframe_topic: '/obj_slam/gtsam/pose_keyframe'
  meas_topic: '/obj_slam/detection/meas_bearing_range'

  # Frame ID
  global_frame: "map"
  base_link_frame: "wamv/base_link"
  camera_link_frame: "wamv/base_link/camera_sensor"
  camera_optical_frame: "wamv/base_link/camera_sensor_optical"
  lidar_frame: "wamv/base_link/lidar_sensor"

num_classes: 10 # 9, 11

# ConvBKI parameters
ConvBKI:
  grid_size: [128, 128, 9] #[256, 256, 2]
  min_bound: [-51.2, -51.2, -0.85] #-1.5
  max_bound: [51.2, 51.2, 0.5] #-1.1
  voxel_sizes: [0.8, 0.8, 0.15] #[0.2, 0.2, 0.1]
  # grid_size: [128, 128, 9] #[256, 256, 2]
  # min_bound: [-51.2, -51.2, -1.85] #-1.5
  # max_bound: [51.2, 51.2, -0.5] #-1.1
  # voxel_sizes: [0.8, 0.8, 0.15] #[0.2, 0.2, 0.1]

  f: 5                 # 5
  publish_map: True    # map publish flag


  # Segmentation Net
  res: 0.25 #0.2
  cr: 0.5


  # rviz color
  # colors: # rgb, grounded_sam2
  #         0: [200, 275, 200] # tree...very light green
  #         1: [0, 102, 0] # grass-shore...darkgreen
  #         2: [160, 160, 160] # concrete_platform...gray
  #         3: [30, 60, 150] # water...dark-blue
  #         4: [255, 30, 30] # redbuoy...red
  #         5: [0, 0, 0] # blackbuoy...black
  #         6: [150, 240, 80] # greenbuoy...lightgreen
  #         7: [255, 128, 0] # orangebuoy...orange
  #         8: [255, 255, 255] # whitebuoy...white

  colors: # rgb, YOLO seg
          0: [220, 220, 220]    # background...lightgray
          1: [255, 30, 30]      # red cone...red
          2: [40, 40, 40]       # black cone...darkgray
          3: [150, 240, 80]     # green cone...lightgreen
          4: [255, 255, 255]    # white cone...white
          5: [0, 0, 0]          # black sphere...black
          6: [255, 128, 0]      # orange sphere...orange
          7: [30, 60, 150]      # water...dark-blue
          8: [160, 160, 160]    # dock...gray
          9: [0, 102, 0]        # land...darkgreen

Obj_SLAM:

  drift_bridge:
    # Timing Gates (ms)
    backtrack_tol_ms: 5.0         # tolerate small backtracks/dupes
    min_dt_floor_ms: 5.0          # ignore micro-bursts
    dt_thresh_ms: 50.0            # time-based KF fallback if no motion

    # Motion Thresholds
    trans_thresh_m: 0.20          # (meter)
    yaw_thresh_deg: 5.0           # (degree)
  
  lm_tracker:
    drop_seconds: 1.5             # when to declare as LOST
    promote_hits: 3               # when to promote
    promote_window: 5             # time window for promotion
    min_score: 0.0                # min detection score