# ROS bag Topics
ros_parameters:
  ## Sensors
  lidar_topic: '/wamv/sensors/lidars/lidar_sensor/points'
  camera_topic: '/wamv/sensors/cameras/camera_sensor/optical/image_raw'
  caminfo_topic: '/wamv/sensors/cameras/camera_sensor/camera_info'

  ## DRIFT
  pose_topic: '/drift/pose'

  ## from objseg_node.py
  det_mask_topic: '/cam_det/segmentation_mask'
  annot_topic: '/cam_det/annotated_image'
  
  ## from pcdFilter_node.py
  filt_pcd_topic: '/lidars/filtered_pcd'      # Filtered LiDAR pcd
  proj_pix_topic: '/lidars/proj_pixel_depth'  # Projected pixels + depth
  # det_topic: '/asv_object_slam/detection/list_raw'

  ## Semantic pcd and map publisher
  semantic_pcd_topic: '/convBKI/semantic_pcd'
  global_pcd_topic: '/convBKI/global_semantic_pcd'
  map_topic: '/convBKI/SemMap_global'                 # not using rn
  var_topic: '/convBKI/VarMap_global'
  # global_map_topic: '/global_semantic_map'
  # global_var_topic: '/global_variance_map'


num_classes: 10 # 9, 11

# Conv BKI
grid_size: [128, 128, 9] #[256, 256, 2]
min_bound: [-51.2, -51.2, -0.85] #-1.5
max_bound: [51.2, 51.2, 0.5] #-1.1
voxel_sizes: [0.8, 0.8, 0.15] #[0.2, 0.2, 0.1]
# grid_size: [128, 128, 9] #[256, 256, 2]
# min_bound: [-51.2, -51.2, -1.85] #-1.5
# max_bound: [51.2, 51.2, -0.5] #-1.1
# voxel_sizes: [0.8, 0.8, 0.15] #[0.2, 0.2, 0.1]

f: 5 #5
publish: True    ## map publish flag


# Segmentation Net
res: 0.25 #0.2
cr: 0.5

# Segmentation weights
seg_path: "./weights/KITTI/max-iou-test.pt"

# ConvBKI weights
model_path: "./weights/KITTI/Epoch1.pt"

# rviz color
# colors: # rgb
#         0: [200, 275, 200]
#         1: [255, 200, 0] # Building or tree...yellow
#         2: [255, 120, 150] # Barrier or concrete_platform...light-pink
#         3: [30, 60, 150] # water...dark-blue
#         4: [255, 30, 30] # Pedestrian or redbuoy...red
#         5: [255, 240, 150] # Pole or blackbuoy...golden-yellow
#         6: [255, 0, 255] # Road or greenbuoy...pink
#         7: [150, 240, 80] # Ground or orangebuoy...lightgreen
#         8: [75, 0, 75] # Sidewalk or whitebuoy...dark-purple
#         9: [0, 175, 0] # Vegetation or other...green
#         10: [245, 150, 100] # Vehicle

# colors: # rgb
#         0: [200, 275, 200] # tree...very light green
#         1: [0, 102, 0] # grass-shore...darkgreen
#         2: [160, 160, 160] # concrete_platform...gray
#         3: [30, 60, 150] # water...dark-blue
#         4: [255, 30, 30] # redbuoy...red
#         5: [0, 0, 0] # blackbuoy...black
#         6: [150, 240, 80] # greenbuoy...lightgreen
#         7: [255, 128, 0] # orangebuoy...orange
#         8: [255, 255, 255] # whitebuoy...white

colors: # rgb, YOLO seg
        0: [220, 220, 220]    # background...lightgray
        1: [255, 30, 30]      # red cone...red
        2: [40, 40, 40]       # black cone...darkgray
        3: [150, 240, 80]     # green cone...lightgreen
        4: [255, 255, 255]    # white cone...white
        5: [0, 0, 0]          # black sphere...black
        6: [255, 128, 0]      # orange sphere...orange
        7: [30, 60, 150]      # water...dark-blue
        8: [160, 160, 160]    # dock...gray
        9: [0, 102, 0]        # land...darkgreen